################
# config.py
# Configurations
################

# Redis
REDIS_URL = "redis://localhost:6379"
INDEX_NAME = "documents"

# Embedding Model
EMBEDDING_MODEL = "text-embedding-ada-002"

# Model
DEFAULT_MODEL = "gpt-4.1-nano"
TEMPERATURE = 0.7
MAX_TOKENS = 3000

# Key Value Cache
CACHE_TTL_SECONDS = 600

# Semantic Cache
SEMANTIC_CACHE_ENABLED = True
SEMANTIC_CACHE_INDEX_NAME = "semantic_cache"
SEMANTIC_CACHE_KEY_PREFIX = "rag:semcache:"
SEMANTIC_CACHE_TOP_K = 3
SEMANTIC_CACHE_MAX_DISTANCE = 0.15

# Proximity Cache
PROXIMITY_CACHE_ENABLED = True
PROXIMITY_CACHE_INDEX_NAME = "proximity_retrieval_cache"
PROXIMITY_CACHE_KEY_PREFIX = "rag:proximity:"
PROXIMITY_CACHE_CAPACITY = 500
PROXIMITY_DISTANCE_TOLERANCE = 0.15
PROXIMITY_RERANK_FACTOR = 3
PROXIMITY_RETRIEVAL_TOP_K = 5
PROXIMITY_EVICTION_POLICY = "LRU"
PROXIMITY_CACHE_MODE = "LSH"
PROXIMITY_LSH_NUM_BITS = 16
PROXIMITY_LSH_BUCKET_CAPACITY = 20
PROXIMITY_LSH_SEED = 42